### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by av-k** [turinggroup/angular-validator#81]
Hello, where i can find?

**Comment by nicooga** [comment]
This library is not published to npm.

I'm using brunch, which automatically loads bower dependencies, but allows/requires to explicitly `require` npm dependencies.

**Result**: since bower resolved to angular 1.3.x, while I needed angular 1.5.x, I was getting strange errors.

**Solution**: link to my fork in your package.json:

~~~json
  "dependencies": {
    "angular-validator": "git+https://github.com/nicooga/angular-validator.git",
~~~
~~~js
require('angular');
// other requires
require('angular-validator');
~~~

It would be nice if the maintainers of the package published the official package to npm though.
